controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

robot_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
    operation_mode: 1
    command_poll_freq: 5

forward_position_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
    interface_name: position
